title: Unmapped Worlds
email: ""
description: >-
  Where every playthrough is a new expedition.
baseurl: ""
url: "https://unmappedworlds.com"

theme: minima
plugins:
  - jekyll-feed

exclude:
   - .github/
   - .gitignore
