title: Unmapped Worlds
email: ""
description: >-
  Where every playthrough is a new expedition.
baseurl: ""
url: "https://unmappedworlds.com"

theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

exclude:
   - .github/
   - .gitignore

permalink: /:title/

collections:
  posts:
    output: true
    permalink: /posts/:title/

sass:
  quiet_deps: true

show_excerpts: true

google_analytics: G-JED68YVFSK
